name: Publish to skynet
on:
  pull_request:
  push:
    branches: [master]

jobs:
  publish:
    name: build and publish to skynet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Publish Website
        run: dotnet publish MetaMask.Blazor.SampleApp -o publish/MetaMask.Blazor.SampleApp -c Release
      - name: Deploy to Skynet
        uses: kwypchlo/deploy-to-skynet-action@main
        with:
          upload-dir: publish/MetaMask.Blazor.SampleApp/wwwroot
          github-token: ${{ secrets.GITHUB_TOKEN }}